# Mục tiêu: Tìm hiểu tổng quan dataset

## Phần 1: Load data

In [1]:
import pandas as pd
import numpy as np

In [3]:
DATA_PATH = "D:/4. Portfolio\Expert/1_Credit_Scoring/portfolio_credit_scoring/data/raw/accepted_2007_to_2018Q4.csv"

In [5]:
%%time
df = pd.read_csv(DATA_PATH, low_memory=False)

CPU times: total: 21.5 s
Wall time: 21.7 s

In [6]:
df.shape

(2260701, 151)

In [7]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(6414.666977882385)

## Phần 2: Kiểu dữ liệu

In [8]:
df.dtypes.value_counts()

float64    113
str         38
Name: count, dtype: int64

In [9]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

Nhận xét:
- Tệp dữ liệu có 151 cột và ~2.26 triệu dòng
- Nặng khoảng 6415 MB
- 113 cột dữ liệu kiểu số và 38 cột dạng string

## Phần 3: Missing value

In [12]:
missing_rate = df.isna().mean().sort_values(ascending=False)

In [13]:
missing_rate = missing_rate.to_frame('missing_rate')

In [14]:
missing_rate.head(20)

                                            missing_rate
member_id                                       1.000000
orig_projected_additional_accrued_interest      0.996173
hardship_reason                                 0.995171
hardship_payoff_balance_amount                  0.995171
hardship_last_payment_amount                    0.995171
payment_plan_start_date                         0.995171
hardship_type                                   0.995171
hardship_status                                 0.995171
hardship_start_date                             0.995171
deferral_term                                   0.995171
hardship_amount                                 0.995171
hardship_dpd                                    0.995171
hardship_loan_status                            0.995171
hardship_length                                 0.995171
hardship_end_date                               0.995171
settlement_status                               0.984852
debt_settlement_flag_date                       0.984852
settlement_term                                 0.984852
settlement_percentage                           0.984852
settlement_date                                 0.984852

In [ ]:
missing_rate